language: objective-c
osx_image: xcode7.3
sudo: false
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - LANGUAGE=en_US.UTF-8
  #- FASTLANE_LANE=ci_commit
matrix:
  include:
   # - osx_image: xcode8
   #   env: FASTLANE_LANE=code_coverage FASTLANE_ENV=default
   # - osx_image: xcode8
    #  env: FASTLANE_ENV=ios10_xcode8
    #- osx_image: xcode7.3
    #  env: FASTLANE_ENV=ios93_xcode73
    #- osx_image: xcode7.3
    #  env: FASTLANE_ENV=ios81_xcode73
before_install:
  # Force bundler 1.12.5 because version 1.13 has issues, see https://github.com/fastlane/fastlane/issues/6065#issuecomment-246044617
 # - gem uninstall bundler -v '>1.12.5' --force || echo "bundler >1.12.5 is not installed"
 # - gem install bundler -v 1.12.5 --no-rdoc --no-ri --no-document --quiet
 # - gem install fastlane --no-rdoc --no-ri --no-document --quiet
  - rvm install ruby-2.2.2
  - gem install cocoapods
  - gem install xcpretty -N
  #- brew update
script:
  - set -o pipefail
  - xcodebuild -workspace JJNetwork.xcworkspace -scheme JJNetwork -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  #- xcodebuild -workspace JJNetwork.xcworkspace -scheme JJNetwork -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO -destination 'platform=iOS Simulator,name=iPad' | xcpretty -c
after_success:
  #- if [ "$FASTLANE_LANE" == "code_coverage" ]; then
  #  bash <(curl -s https://codecov.io/bash);
  # fi
after_failure:
# - cat -n ~/Library/Logs/scan/*
# - cat -n $TMPDIR/com.apple.dt.XCTest-status/Sessio*.log
# - cat -n ~/Library/Logs/DiagnosticReports/xctest*.crash
